
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Digito = 18;
  public static final int Conjunto = 5;
  public static final int CeroOUna = 15;
  public static final int Especial = 21;
  public static final int Diagonales = 19;
  public static final int LlaveCierra = 7;
  public static final int LlaveAbierta = 6;
  public static final int Coma = 22;
  public static final int Cadena = 20;
  public static final int EOF = 0;
  public static final int SignosEspeciales = 16;
  public static final int error = 1;
  public static final int GuionCurvo = 10;
  public static final int Mayorque = 9;
  public static final int Guion = 8;
  public static final int Punto = 11;
  public static final int DoblePorcentaje = 3;
  public static final int Letra = 17;
  public static final int CeroOMas = 14;
  public static final int UnoOMas = 13;
  public static final int Disyuncion = 12;
  public static final int PuntoComa = 4;
  public static final int DosPuntos = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DosPuntos",
  "DoblePorcentaje",
  "PuntoComa",
  "Conjunto",
  "LlaveAbierta",
  "LlaveCierra",
  "Guion",
  "Mayorque",
  "GuionCurvo",
  "Punto",
  "Disyuncion",
  "UnoOMas",
  "CeroOMas",
  "CeroOUna",
  "SignosEspeciales",
  "Letra",
  "Digito",
  "Diagonales",
  "Cadena",
  "Especial",
  "Coma"
  };
}

